### ISSUE TITLE
Doesn't seem to work with Intellij IDEA 14.1 (build 141.177)

### ISSUE THREAD

**Issue by martinduparc** [raket/idea-silverstripe#62]
The plugin doesn't seem to work with the latest Intellij IDEA update (build 141.177). It installs fine but the Silverstripe file type (*.ss) isn't recognized.

**Comment by Firesphere** [comment]
Works fine for me. Try updating maybe?

**Comment by martinduparc** [comment]
I had to add the file type manually, thanks!
