### ISSUE TITLE
Any plans for netbeans too?

### ISSUE THREAD

**Issue by Chris2011** [raket/idea-silverstripe#64]
Hey,

do you plan to support netbeans?
Would be very nice.

Regards

Chris

**Comment by Firesphere** [comment]
NetBeans is very different from IntelliJ, so I doubt this plugin can be ported, I think it'll need a complete build from scratch.

**Comment by MarcusDalgren** [comment]
Yeah the parsing stuff that tokenizes the files might be reusable but the rest is very dependent on the Jetbrains IDE API. We for example inherit their parsers for html/css/js so the plugin doesn't have to worry about those parts of the file.
