### ISSUE TITLE
This plugin breaks autocompletion for Object::create() method calls

### ISSUE THREAD

**Issue by memdev** [raket/idea-silverstripe#66]
I just noticed that this plugin breaks autocompletion for method calls like

```php
FieldList::create()->
```
It should have shown the methods defined in FieldList class. Instead it displays a red tooltip saying "No suggestions".

When disabling this plugin, autocompletion works as expected.

It would be great to have this fixed so we can use the benefits of Object::create(), method chaining and autocompletion.

**Comment by MarcusDalgren** [comment]
Fix is coming up!

**Comment by MarcusDalgren** [comment]
This is fixed now in the new release.

**Comment by anselmdk** [comment]
@MarcusDalgren have you pushed that release to Github yet?

**Comment by MarcusDalgren** [comment]
@anselmdk Yes the fix is in the phpstorm-61 branch. I really should merge that back in to master.

**Comment by memdev** [comment]
Works great! Thank you!! :-)

**Comment by axyr** [comment]
Very very very nice !
