### ISSUE TITLE
Argument for @NotNull parameter 'file' of ... must not be null

### ISSUE THREAD

**Issue by jyrkij** [raket/idea-silverstripe#67]
Have been getting this error for some time now. Any chances at looking at this? There are several (91 in a day) errors with somewhat differing [stack traces](https://gist.github.com/jyrkij/e470f13dc1aedeb430e34e022eb1cc80).

/cc @FinBoWa

**Comment by MarcusDalgren** [comment]
Fix is coming up!

**Comment by MarcusDalgren** [comment]
I hope I got them all.
Let me know if the error persists and if you can post stack traces again then that is super awesome!
